apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  sources:
  - repoURL: 'https://immich-app.github.io/immich-charts'
    chart: immich
    targetRevision: 0.9.3
    helm:
      values: |-
        # These entries are shared between all the Immich components
        image:
          tag: v1.135.1

        immich:
          persistence:
            # Main data store for all photos shared between different components.
            library:
              # Automatically creating the library volume is not supported by this chart
              # You have to specify an existing PVC to use
              existingClaim: photos

        # Dependencies

        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: false

        # Immich components

        server:
          enabled: true
          image:
            repository: ghcr.io/immich-app/immich-server
            pullPolicy: IfNotPresent
          
          ingress:
            main:
              enabled: true
              hosts:
                - host: immich.familielux.org
                  paths:
                    - path: "/"

        machine-learning:
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
          enabled: true
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            pullPolicy: IfNotPresent
          env:
            TRANSFORMERS_CACHE: /cache
          persistence:
            cache:
              enabled: true
              size: 10Gi
              # Optional: Set this to pvc to avoid downloading the ML models every start.
              type: pvc
              accessMode: ReadWriteOnce
              storageClass: local-path

        envFrom:
          - secretRef:
              name: immich-postgres-user

        env:
          DB_HOSTNAME: 'immich-postgres-rw'
  - repoURL: https://github.com/CreateRandom/homelab-apps
    path: templates/immich/extra
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  project: default