apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'immich'
spec:
  sources:
  - repoURL: 'https://immich-app.github.io/immich-charts'
    chart: immich
    targetRevision: 0.9.0
    helm:
      valueFiles:
      - $values/templates/immich/values.yaml
  - repoURL: 'https://github.com/CreateRandom/homelab-apps'
    targetRevision: main
    ref: values
  - repoURL: https://github.com/CreateRandom/homelab-apps
    path: templates/immich/extra
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  project: default