apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: 2.1.0
    helm:
      values: |-
        config:
          widgets:
            - kubernetes:
                cluster:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
                  label: "cluster"
                nodes:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
          services:
            
    
          kubernetes:
            mode: cluster

        # The service account is necessary to allow discovery of other services
        serviceAccount:
          create: true
          name: homepage

        # This enables the service account to access the necessary resources
        enableRbac: true
        image:
          tag: v1.3.2
        ingress:
          main:
            enabled: true
            annotations:
              # Example annotations to add Homepage to your Homepage!
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: "Homepage"
              gethomepage.dev/description: "Dynamically Detected Homepage"
              gethomepage.dev/group: "Dynamic"
              gethomepage.dev/icon: "homepage.png"
            hosts:
              - host: homepage.familielux.org
                paths:
                  - path: /
                    pathType: Prefix
        env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: homepage.familielux.org
    chart: homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      selfHeal: true
