apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  sources:
  - repoURL: 'https://charts.kasten.io/'
    chart: kasten/k10
    targetRevision: 7.5.7
    helm:
      values: |-      
        ingress:
          create: true
          urlPath: "k10.familielux.org"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kasten-io
  project: default